import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
      backgroundColor: '#fff',
      height: 'auto',
    },
    closeButton: {
      backgroundColor: '#1f1f1f',
      borderRadius: 5,
      width: 180,
      height: 45,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    closeButtons: {
      marginTop: 10,
      backgroundColor: '#1f1f1f',
      borderRadius: 5,
      width: 120,
      height: 45,
      marginBottom: 13,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    closeButtonText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    closeButtonTexts: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    buttonfield: {
      width: '100%',
      justifyContent: "center",
      alignItems: "center",
      marginTop: 10,
    },
    closeButtonX:{
      paddingTop:55,
      paddingRight:20,
    },
    closeButtonXs:{
      paddingTop:13,
      paddingRight:20,
    },
    circle: {
      backgroundColor: '#00FF7F',
      borderRadius: 50,
      width: 64,
      height: 64,
      justifyContent: 'center',
      alignItems: 'center',
    },
    circleContainer: {
      position: 'absolute',
      bottom: '7%',
      right: 20,
      zIndex: 2,
    },
    circleContainerd: {
      position: 'absolute',
      bottom: '34%',
      right: 20,
      zIndex: 2,
    },
    centeredView: {
      flex: 1,
    },
    centeredViewNewApo: {
      flex: 1,
      backgroundColor: '#000000aa',
      justifyContent: 'center',
      alignItems: 'center',
    },
    contentContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalView: {
      backgroundColor: '#fff',
      marginTop: '42%',
      borderRadius: 5,
      width: '100%',
      height: '130%',
      padding: 0,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 1,
      shadowRadius: 10,
      elevation: 5,
      top: -120,
    },
    modalViewNewApo: {
      backgroundColor: '#fff',
      borderRadius: 5,
      width: '98%',
      height: '80%',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 1,
      shadowRadius: 10,
      elevation: 5,
    },
    input1: {
      borderWidth: 1,
      padding: 15,
      width: '90%',
      marginLeft: '5%',
      textAlign: 'left',
    },
    input2: {
      borderWidth: 1,
      padding: 15,
      width: '90%',
      height: 100,
      marginLeft: '5%',
      marginTop: 5,
      textAlign: 'left',
    },
    title: {
      fontSize: 20,
      fontWeight: 'bold',
      marginLeft: 3,
      marginBottom: 14,
      marginTop:2
    },
    content: {
      fontSize: 16,
    },
    contentLeft: {
      fontSize: 16,
      
    },
    contenttime: {
      fontSize: 16,
      height: '100%',
      width: 100,
      textAlign: 'center',
      paddingTop: '7%',
    },
    contain: {
      backgroundColor: '#f7feff',
      height: 80,
      width: '100%',
      marginTop: 4,
      marginBottom: 4,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      justifyContent: 'flex-start',
    },
    scrollContainer: {
      flexGrow: 1,
      height: 'auto',
      width: '100%',
      alignItems: 'center',
      backgroundColor: '#fff',
      paddingBottom: 20,
    },
    calendarline: {
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      height: 27,
      backgroundColor: '#585858',
    },
    modalText: {
      marginBottom: 10,
    },
    searchBox: {
      width: '100%',
      height: 40,
      padding: 8,
      fontSize: 16,
      borderWidth: 1,
      borderColor: '#ccc',
      paddingHorizontal: 10,
      marginLeft: 5,
      borderRadius: 5,
    },
    highlight: {
      backgroundColor: 'yellow',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      width: '100%',
      marginBottom: 20,
    },
    apoinvHeader: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      width: '100%',
      marginBottom: 20,
    },
    apoinvView:{
      height: '100%',
      width: '100%',
      backgroundColor: '#ffffff',
    },
    modalHeaderText: {
      fontSize: 20,
      fontWeight: 'bold',
      marginRight: '26%',
      marginTop: '2%',
    },
    invHeaderText: {
      fontSize: 20,
      fontWeight: 'bold',
      marginRight: '21%',
      marginTop: '14%',
    },
    invnowText: {
      fontSize: 22,
      fontWeight: 'bold',
      marginLeft: '5%',
    },
    likeedit: {
      flexDirection: 'row', // 要素を横に並べる
      justifyContent: 'space-between', // 要素間のスペースを均等に分配
      paddingHorizontal: '12%', // 左右のパディング
      alignItems: 'center', // 縦方向に中央揃え
      marginRight:'6%',
      marginTop: '3%',
    },
    likeedits: {
      flexDirection: 'row', // 要素を横に並べる
      justifyContent: 'space-between', // 要素間のスペースを均等に分配
      paddingHorizontal: '12%', // 左右のパディング
      alignItems: 'center', // 縦方向に中央揃え
      marginTop: '3%',
    },
    item: {
      alignItems: 'center',
    },
    label: {
      fontSize: 12,
      marginTop: 8,
    },
    lightLine: {
      height: 1,
      backgroundColor: '#000000',
      opacity: 0.2,
      marginTop: '2%',
    },
    lightLine2: {
      height: 1,
      backgroundColor: '#000000',
      opacity: 0.2,
      marginTop: '35%',
    },
    headtitle: {
      fontSize: 16,
      fontWeight: 'bold',
      marginTop: '5%',
      marginLeft: '3%',
    },
    detail: {
      fontSize: 16,
      marginTop: '3%',
      marginLeft: '3%',
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 30,
      marginTop: 50,
    },
    friendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      width: 230,
      marginLeft: 27,
      height: 62,
    },
    friendImage: {
      width: 60,
      height: 60,
      borderRadius: 55,
      marginRight: 10,
    },
    Imagedef:{
      height: 70,
      width: 70,
      top: -4,
      left: -6,
    },
    friendscroll:{
      width: '95%',
    },
    friendName: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    inviteButton: {
      backgroundColor: 'blue',
      borderRadius: 10,
      width: 160,
      height: 50,
      marginTop: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    inviteButtonText: {
      color: 'white',
      fontSize: 22,
      fontWeight: 'bold',
    },
    talkroomRef: {
      width: '100%',
      marginTop: '3%',
    },
    ibar: {
      width: '2%',
      height: '100%',
      backgroundColor: '#f13434',
      opacity: 0.2,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 10,
      marginVertical: 5,
      alignContent: 'flex-start',
      width: '100%',
    },
    searchIconContainer: {
      padding: 10,
      marginLeft: 10,
    },
    ApoIconContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 10,
      marginVertical: 5,
      alignContent: 'flex-start',
      width: '100%',
      left: '76%',
    },
    searchBoxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 10,
      alignContent: 'flex-start',
      width: '80%',
    },
    closeIconContainer: {
      position: 'absolute',
      top: -3,
      right: -5,
      padding: 10,
    },
    notificationIconContainer: {
      position: 'absolute',
      top: 5,
      right: 8,
      backgroundColor: 'red',
      borderRadius: 50,
      width: 20,
      height: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    notificationBadgeText: {
      color: '#fff',
      fontWeight: 'bold',
    },
    noAppointmentContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 100,
    },
    noAppointmentText: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    friendinv: {
      height: 103,
      width: '90%',
      backgroundColor: '#f7feff',
      marginLeft: 20,
    },
    selectFriend: {
      marginLeft: 20,
      marginTop: 15,
      fontSize: 20,
      fontWeight: 'bold',
    },
    selectLocate: {
      marginLeft: 20,
      marginTop: 5,
      fontSize: 20,
      fontWeight: 'bold',
    },
    unknowntext: {
      marginLeft: 40,
      fontSize: 18,
      fontWeight: '500',
      marginTop: 5,
      color: '#808080',
    },
    iconbox: {
      flexDirection: 'row',
    },
    icon: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: '#fff',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#ccc',
      marginTop:5,
    },
    friendIcon: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: '#fff',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#ccc',
    },
    closeIcon: {
      position: 'absolute',
      top: -1,
      right: -3,
      borderRadius: 500,
      backgroundColor: '#fff',
      borderWidth:0.5,
      borderColor:'#ccc',
    },
    iconname: {
      width: 60,
      marginLeft:10,
      height: '100%',
      textAlign: 'center',
    },
  });

  export default styles;