name: Update Version Badge

on:
  push:
    branches:
      - main  # このワークフローをmainブランチにプッシュしたときに実行

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read version from file
      id: read-version
      run: |
        VERSION=$(cat version.txt)  # バージョン情報をファイルから読み取る
        echo "::set-output name=version::$VERSION"
    
    - name: Create version badge
      run: |
        VERSION=${{ steps.read-version.outputs.version }}
        echo "https://img.shields.io/badge/Version-$VERSION-blue" > version-badge-url.txt  # バッジのURLをファイルに書き込む
    
    - name: Commit and push badge changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add version-badge-url.txt
        git commit -m "Update version badge"
        git push
